[build]
  command = "npm run build"
  publish = "dist"
  functions = "backend/src/functions"

[functions]
  node_bundle = true
  external_node_modules = ["mongoose", "bcryptjs", "jsonwebtoken"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
